"""Reproducible original printed guitar studies with labeled image variants.

Synthetic distortions are never described as real photographs or handwriting.
Real camera and handwriting cases must be separately added with provenance.
"""
import json
import random
from pathlib import Path

import cairosvg
import verovio
from PIL import Image, ImageEnhance, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "artifacts/omr-corpus"


def pitch(midi):
    steps = ["C", "C", "D", "D", "E", "F", "F", "G", "G", "A", "A", "B"]
    alter = "<alter>1</alter>" if midi % 12 in {1, 3, 6, 8, 10} else ""
    return f"<pitch><step>{steps[midi % 12]}</step>{alter}<octave>{midi // 12 - 1}</octave></pitch>"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = []
    for study in range(20):
        rng = random.Random(104729 + study)
        category = "printed-chords" if study >= 12 else "printed-melody"
        notes = []
        xml = f'<score-partwise version="4.0"><work><work-title>StringMap reference {study + 1}</work-title></work><identification><creator type="composer">StringMap original test study</creator></identification><part-list><score-part id="P1"><part-name>Guitar</part-name></score-part></part-list><part id="P1">'
        for m in range(4):
            xml += f'<measure number="{m + 1}">'
            if m == 0: xml += '<attributes><divisions>4</divisions><key><fifths>0</fifths></key><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>'
            if m == 0: xml += '<direction><sound tempo="90"/></direction>'
            for beat in range(4):
                pitches = rng.choice([[60, 64, 67], [62, 65, 69], [59, 62, 67], [60, 65, 69]]) if study >= 12 else [rng.choice([60, 62, 64, 65, 67, 69, 71, 72])]
                for n, midi in enumerate(pitches):
                    xml += f'<note id="m{m}b{beat}n{n}">{"<chord/>" if n else ""}{pitch(midi)}<duration>4</duration><type>quarter</type><stem>up</stem></note>'
                    notes.append({"midi": midi, "onset": m * 4 + beat, "duration": 1})
            xml += '</measure>'
        xml += '</part></score-partwise>'
        name = f"study-{study + 1:02d}"
        (OUT / f"{name}.musicxml").write_text(xml)
        tk = verovio.toolkit(); tk.setOptions({"pageWidth": 2100, "pageHeight": 1200, "scale": 60, "adjustPageHeight": True, "breaks": "none", "header": "none", "footer": "none"})
        if not tk.loadData(xml): raise RuntimeError("Could not engrave reference")
        svg = tk.renderToSVG(1)
        clean = OUT / f"{name}-clean.png"
        cairosvg.svg2png(bytestring=svg.encode(), write_to=str(clean), output_width=2600, background_color="white")
        image = Image.open(clean).convert("RGB")
        variants = {"clean": image, "rotate": image.rotate(4, resample=Image.Resampling.BICUBIC, expand=True, fillcolor="white"),
                    "blur": image.filter(ImageFilter.GaussianBlur(0.8)), "dim": ImageEnhance.Brightness(image).enhance(0.6),
                    "perspective": image.transform(image.size, Image.Transform.PERSPECTIVE, (1, .08, 0, .01, 1, 0, .000025, .000018), resample=Image.Resampling.BICUBIC, fillcolor="white")}
        for variant, page in variants.items():
            path = OUT / f"{name}-{variant}.jpg"; page.save(path, quality=65 if variant == "blur" else 92)
            manifest.append({"id": f"{name}-{variant}", "image": path.name, "reference": f"{name}.musicxml", "category": category,
                "capture": "engraved" if variant == "clean" else "synthetic-" + variant, "expected": notes,
                "provenance": "Original deterministic StringMap test composition; generated by build_corpus.py. Concert-pitch treble notation.", "license": "Repository-owned test material"})
    # Non-musical photographs must not become plausible scores.
    for name, color in [("blank", "white"), ("black", "black")]:
        path = OUT / f"negative-{name}.jpg"; Image.new("RGB", (1600, 1200), color).save(path)
        manifest.append({"id": f"negative-{name}", "image": path.name, "category": "unsupported", "capture": "synthetic", "expected": [], "provenance": "Generated uniform image", "license": "Repository-owned test material"})
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(json.dumps({"images": len(manifest), "distinct_scores": 20, "real_camera_photos": 0, "handwriting": 0, "path": str(OUT)}))


if __name__ == "__main__": main()
